### ISSUE TITLE
jfr file produces InvalidFlrFileException

### ISSUE THREAD

**Issue by hamilyon** [chrishantha/jfr-flame-graph#9]
$ /usr/java/jdk1.8.0_144/bin/java $JVM_ARGS -jar target/flamegraph-output-*.jar -ot folded -f ~/flight_recording_17080orgapachecatalinastartupBootstrapstart14457.jfr 
```
Could not load the JFR file.
If the JFR file is compressed, try the decompress option
com.jrockit.mc.flightrecorder.internal.parser.binary.InvalidFlrFileException
Exception in thread "main" java.lang.RuntimeException: com.jrockit.mc.flightrecorder.internal.parser.binary.InvalidFlrFileException
	at com.jrockit.mc.flightrecorder.FlightRecordingLoader.loadFile(FlightRecordingLoader.java:194)
	at com.github.chrishantha.jfr.flamegraph.output.JFRToFlameGraphWriter.process(JFRToFlameGraphWriter.java:112)
	at com.github.chrishantha.jfr.flamegraph.output.Application.main(Application.java:48)
Caused by: com.jrockit.mc.flightrecorder.internal.parser.binary.InvalidFlrFileException
	at com.jrockit.mc.flightrecorder.internal.parser.binary.ChunkHeader.<init>(ChunkHeader.java:23)
	at com.jrockit.mc.flightrecorder.FlightRecordingLoader$ChunkBuffer.readHeader(FlightRecordingLoader.java:230)
	at com.jrockit.mc.flightrecorder.FlightRecordingLoader.<init>(FlightRecordingLoader.java:79)
	at com.jrockit.mc.flightrecorder.FlightRecordingLoader.loadFile(FlightRecordingLoader.java:157)
	at com.jrockit.mc.flightrecorder.FlightRecordingLoader.loadFile(FlightRecordingLoader.java:192)
```

jmc opens saved file just fine

**Comment by chrishantha** [comment]
Did you try decompress option as mentioned in the error message?

**Comment by hamilyon** [comment]
That worked, thank you
